name: pragma-opensource
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - pyarrow>=17.0
  - pyyaml>=6.0
  - pytorch>=2.5
  - pip
  - pip:
      - lmdb>=1.5
      - transformers>=4.45
